name: Lint App

on:
  push:
    paths:
      - 'app/**'
    branches:
      - '*'

jobs:
  lint:
    name: Lint App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn run lint