name: Lint Terraform

on:
  push:
    paths:
      - 'terraform/**'
    branches:
      - '*'

jobs:
  lint:
    name: Lint Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout source code
        uses: actions/checkout@main
      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: latest
      - name: Run TFLint
        run: tflint -f compact
