name: Test Frontend App

on:
  push:
    paths:
      - 'app/**'
    branches:
      - '*'

jobs:
  test:
    name: Test Frontend App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout source code
        uses: actions/checkout@main
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn run lint
      - name: Run Tests
        run: yarn run test
